name: Publish to CurseForge

on: workflow_dispatch
    
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: Upload artifact
      uses: itsmeow/curseforge-upload@v3
      with:
        token: ${{ secrets.CURSEFORGE_TOKEN }}
        project_id: 380814
        game_endpoint: minecraft
        file_path: target/SimpleClans.jar
        changelog: Implemented war and protection
        display_name: v2.15.0
        game_versions: 7915,7667,7330,7105,6588,630,585,531
        release_type: release
        relations: vault:optionalDependency,worldguard:optionalDependency,grief-prevention:optionalDependency
